name: WorshipFlow
options:
  bundleIdPrefix: com.dgutierrezd
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 5
targets:
  WorshipFlow:
    type: application
    platform: iOS
    sources:
      - WorshipFlow
    settings:
      base:
        INFOPLIST_KEY_UIUserInterfaceStyle: Light
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.dgutierrezd.worshipflow
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: UMM993JNZH
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "WorshipFlow needs access to your photo library to set a band image."
        INFOPLIST_KEY_CFBundleDisplayName: "Worship Manager"
